before_install:
  - sudo apt-get install ant
  - git clone https://github.com/facebook/buck.git --branch master --depth=1 $HOME/buck
  - cd $HOME/buck && ant
  - $HOME/buck/bin/buck --version

install:
  - $HOME/buck/bin/buck fetch //...
  - $HOME/buck/bin/buck build :soloader
